name: Build APK

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: .fvmrc

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - run: echo "${{secrets.KEY_PROPERTIES}}" | base64 --decode > ${{env.KEY_PROPERTIES_PATH}}
      - run: echo "${{secrets.KEY_JKS}}" | base64 --decode > ${{env.KEY_JKS_PATH}}

      - name: Build APK
        run: flutter build apk --release --target-platform android-arm64 --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 30

env:
  KEY_PROPERTIES_PATH: "./android/key.properties"
  KEY_JKS_PATH: "./android/keystore.jks"
